### ISSUE TITLE
有点菜，问个问题，这个音乐库的地址和用户名密码 去那里获取

### ISSUE THREAD

**Issue by huangxulei** [Zhoucheng133/netPlayer-Next#1]
下载了你的源码，想测试下，但是不清楚这个怎么用。

**Comment by Zhoucheng133** [comment]
这是一个需要搭建Navidrome音乐库才能使用的音乐客户端，可以根据本地的音乐文件来构建一个自己的音乐系统

下面是搭建这个服务器最简单的办法：

1. 你需要先前往[Navidrome releases页面](https://github.com/navidrome/navidrome/releases)下载Navidrome服务
2. 使用终端或者cmd输入这样的命令：
```bash
[navidrome程序路径] --musicfolder "[音乐文件夹路径]"
```
注意修改中括号内的路径，音乐文件夹路径下要有音乐文件
3. 启动的默认端口号为4533，比如你的Navidrome运行在本地，那么可以用浏览器打开`http://localhost:4533`进入Navidrome，第一次打开就会设定用户名和密码

如果你想在其它设备上连接到这个音乐服务器，那么这个Navidrome服务的地址为`http://[Navidrome服务器ip地址]:4533`，注意更换中括号内的ip地址

其它帮助你可以参考[netPlayer帮助](https://github.com/Zhoucheng133/net-player/blob/master/HELP.md)
