### ISSUE TITLE
Can you please release appimage for Linux users

### ISSUE THREAD

**Issue by fengwang** [Zhoucheng133/netPlayer-Next#2]
This can be easily done following [this tutorial](https://odilondamasceno.medium.com/creating-appimage-with-flutter-d19ef8b53158). Or I can submit a PR for this feature.

**Comment by Zhoucheng133** [comment]
I am not sure that all the dependencies support Linux and I don't learn much about developing Linux apps. You can try it on you own Linux PC.
PR is acceptable.
