### ISSUE TITLE
重启后音量显示与实际音量不符。

### ISSUE THREAD

**Issue by sangchengfang** [Zhoucheng133/netPlayer-Next#3]

**Comment by sangchengfang** [comment]
希望增加歌单一键播放功能

**Comment by sangchengfang** [comment]
希望打开的时候能记住上一次关闭的时候播放的歌曲和播放列表

**Comment by sangchengfang** [comment]
目前我遇到一个问题是音量调小之后，关闭软件重新打开播放，虽然音量显示已经调小了，但是实际播放的音量还是很大，即重启后音量显示与实际音量不符。

**Comment by Zhoucheng133** [comment]
> 希望增加歌单一键播放功能

你可以双击播放第一首歌曲，然后按照你想要的播放模式顺序播放


> 希望打开的时候能记住上一次关闭的时候播放的歌曲和播放列表

这个功能一直都有，除非你在设置中手动关闭了`保存播放的歌曲`功能



> 目前我遇到一个问题是音量调小之后，关闭软件重新打开播放，虽然音量显示已经调小了，但是实际播放的音量还是很大，即重启后音量显示与实际音量不符。

这个问题查证后的确存在，会在下一个版本中更新

**Comment by Zhoucheng133** [comment]
已在[v3.3.2](https://github.com/Zhoucheng133/netPlayer-Next/releases/tag/v3.3.2)中修复

**Comment by sangchengfang** [comment]
感谢
